### ISSUE TITLE
Pouzivanie nastavenia expozicneho casu

### ISSUE THREAD

**Issue by MicSing** [TIS2017/Spektrometer#11]
Moznost v directshow je, ale ked si pytam napriklad defaultnu hodnotu, tak funkcia vrati false teda zlyhala.
Link na funkciu: http://www.aforgenet.com/framework/docs/html/c28a265e-5896-ecd0-0fa0-76b47f6602e0.htm

**Comment by pavelpetrovic** [comment]
co vrati GetCameraPropertyRange() ?
a co vrati SetCameraProperty() ?

mate moznost vyskusat aj nejaku inu kameru?  
(ak by to na inej islo a na tejto nie, tak je jasne, ze tato kamera resp. jej driver to neumoznuje)
p.

**Comment by MicSing** [comment]
Po viacerých testovaniach som zistil, že tieto nastavenia fungujú iba ak to driver umožňuje ako ste napísali.
A zároveň tieto nastavenia sú už dostupné v prototype #10 .

**Comment by pavelpetrovic** [comment]
fajn a s tou kamerou, ktorá je v spektrometri, idú?

**Comment by MicSing** [comment]
áno, práve na nej som to skúšal

**Comment by pavelpetrovic** [comment]
to znie optimisticky! :)
takže tá kamera neprispôsobuje expozíciu podľa celkového osvetlenia prostredia?
neskúšali ste to zistiť?
