### ISSUE TITLE
Navrh

### ISSUE THREAD

**Issue by radohecko** [TIS2017/Spektrometer#18]

**Comment by pavelpetrovic** [comment]
vďaka za pridanie pracovnej verzie návrhu s návrhom GUI. aký je stav? pracuje sa na tom? mám sa vyjadriť a potom to pošlete zadávateľovi, alebo nejaký iný? v commitoch, prosím, uveďte takéto info, aby som vedel, ako na to reagovať...

vyjadrím sa teda zatiaľ k tejto verzii:
- v texte vidím "možnosť vybrania riadku a stĺpca", ale na obrázku vidím "Y" a "H", nejak nerozumiem 
- vidím tam "defaulte", asi myslíte "defaults" alebo "default"
- measurment -> measurement
- neviem, čo si mám predstaviť pod panelom "Záznam z kamery", ktorý je na všetkých obrázkoch, ale nikde nie je vysvetlený
- nerozumiem aky je rozdiel medzi video proc amp  a  camera control a preco v jednom rezime je viac nastaveni ako v druhom
- "tak sa na RGB grafe zvýraznia ich polohy" -> ako sa zvýraznia? a nerozumiem, či sa to týka všetkých takých hodnôt, alebo len peakov, čiže či tie peaky, ktoré sú pod touto hodnotou sa nezobrazujú? nie je to jednoznačne zrozumiteľné. prečítali ste si to po sebe?
- "vyplnenia plochy grafu farbami zvoleného výrezu "  -> nerozumiem, čo je farba zvoleného výrezu
- pri zobrazení rozdielu nerozumiem ako sa určí statický obrázok, ktorý sa má od aktuálneho odpočítavať
- kalibrácia - tlačidlo + rozširuje len o 3. bod alebo aj ďalšie 4,5,...? ak len tretí, tak by mohol byť rovno zobrazený a len zaškrtnuteľný nejakým checkboxom (?)
- a vlnová dĺžka zodpovedá ktorému za tých bodov? nemala by sa zadať pre všetky tri body?
- ak som dobre pochopil cez import sa nebude dať načítať aj graf, lebo ten sa zasa dá vypočítať z načítaného obrázka v programe (?) ale aj tak by položky v importe mohli byť označené rovnakými lablami ako v exporte, aby v tom mal používateľ jasno, čo importuje a exportuje
- na žiadnom obrázku neviem nájsť nasledujúce požiadavky z katalógu požiadaviek:
   - 3.1.2.a
   - 3.1.2.1.e, 3.1.2.1.f, 3.1.2.1.i
   - 3.1.2.2.n (a výška má mať nastaviteľný rozmer)
   - 3.1.2.2.o.1
   - 3.1.2.2.o.3 - globálne max.
   - 3.1.2.2.o.5

ak to dôsledne zapracujete, pošlite to zadávateľovi (alebo ešte lepšie - osobne s ním prediskutujte), ak si nie ste istí, tak to ešte raz pošlite mne.
