### ISSUE TITLE
Camera view

### ISSUE THREAD

**Issue by radohecko** [TIS2017/Spektrometer#41]

**Comment by MicSing** [comment]
@radohecko 
- nastavovanie kamery
	Ak sa vyberie nova kamera nech sa zmeni button Set (Set => Set*) alebo na cokolvek ta napadne, aby bolo vidno ci je nastavena alebo nie
	Ak sa ide nastavit nova je potrebne, aby sa najskor vypla stara
	Pri vytvoreni CameraView by sa malo kontrolovat ci je nastavena kamera a ak je mala by byt vybrana v Comboboxe (GetCameraIndex vrati -1 ak nebola nastavena)
- nastavovanie vyseku z obrazka (Y == rowIndex, H == rowCount)
	Pri vytvarani CameraView by sa tam uz mali nastavit hodnoty. V ImageControllery ich vies ziskat (GetRowIndex, GetRowCount)
	Po ich zmene by sa malo tlacidlo Set tiez nejako zmenit, aby si vedel ci uz su nastavene alebo nie
	Na ich nastavenie mas tiez funkcie v ImageControllery (SetRowIndex, SetRowCount)
- Settings
	Funkciu mas v CameraControllery (ShowSettings)

**Comment by radohecko** [comment]
jo pozriem sa nato
